# Generated by Django 5.1.1 on 2024-12-08 04:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_no', models.CharField(max_length=10, verbose_name='股票代號')),
                ('stk_na', models.CharField(max_length=50, verbose_name='股票名稱')),
                ('stk_ab', models.CharField(blank=True, max_length=50, null=True, verbose_name='簡稱')),
                ('establishment_date', models.CharField(blank=True, max_length=8, null=True, verbose_name='成立日期')),
                ('listing_Date', models.CharField(blank=True, max_length=8, null=True, verbose_name='上市日期')),
                ('stk_ps', models.IntegerField(default=0, verbose_name='特別股數')),
                ('stk_cs', models.IntegerField(default=0, verbose_name='普通股數')),
            ],
            options={
                'verbose_name': '公司基本資訊',
                'verbose_name_plural': '公司基本資訊',
                'db_table': 'basic_company_information',
                'indexes': [models.Index(fields=['stk_ab'], name='basic_compa_stk_ab_735f80_idx')],
                'constraints': [models.UniqueConstraint(fields=('stk_no',), name='basic_company_information unique key')],
            },
        ),
        migrations.CreateModel(
            name='TradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField(default=django.utils.timezone.now, verbose_name='最後成交日期')),
                ('funds_invested', models.IntegerField(verbose_name='投入資金')),
                ('funds_remaining', models.IntegerField(help_text='買賣後剩下資金', verbose_name='剩餘資金')),
                ('shares', models.IntegerField(verbose_name='持有股數')),
                ('price', models.FloatField(verbose_name='價格')),
                ('price_avg', models.FloatField(verbose_name='成交均價')),
                ('value_total', models.IntegerField(help_text='包含成本', verbose_name='總價值')),
                ('stk_no_id', models.ForeignKey(help_text='股票代號', on_delete=django.db.models.deletion.CASCADE, to='trade.basiccompanyinformation')),
            ],
            options={
                'verbose_name': '庫存總計',
                'verbose_name_plural': '庫存總計',
                'db_table': 'trade_summary',
            },
        ),
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, verbose_name='委託單號')),
                ('buy_sell', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell'), ('', 'Other')], max_length=1, verbose_name='買賣')),
                ('t_date', models.DateField(default=django.utils.timezone.now, verbose_name='成交日期')),
                ('price', models.FloatField(verbose_name='成交價格')),
                ('qty', models.IntegerField(verbose_name='成交數量')),
                ('qty_price', models.IntegerField(help_text='股數x金額', verbose_name='價值金額')),
                ('fee', models.IntegerField(verbose_name='手續費')),
                ('tax', models.IntegerField(verbose_name='交易稅')),
                ('note', models.CharField(max_length=30, verbose_name='備註')),
                ('funds_invested', models.IntegerField(help_text='只有設定時會變動', verbose_name='投入資金')),
                ('funds_remaining', models.IntegerField(help_text='買賣後剩下資金，投入資金變動時也會增減', verbose_name='剩餘資金')),
                ('shares', models.IntegerField(verbose_name='持有股數')),
                ('price_avg', models.FloatField(verbose_name='成交均價')),
                ('hold_qty_price', models.IntegerField(help_text='股數x金額', verbose_name='持有價值金額')),
                ('stk_no_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.basiccompanyinformation', verbose_name='股票代號')),
            ],
            options={
                'verbose_name': '交易明細',
                'verbose_name_plural': '交易明細',
                'db_table': 'trade_details',
                'indexes': [models.Index(fields=['order_no', 'stk_no_id', 'qty'], name='trade_detai_order_n_b39ccf_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_no', 'stk_no_id', 'qty'), name='trade_details unique key')],
            },
        ),
    ]
