# Generated by Django 5.1.1 on 2024-11-26 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_no', models.CharField(max_length=10, verbose_name='股票代號')),
                ('stk_na', models.CharField(max_length=50, verbose_name='股票名稱')),
            ],
            options={
                'verbose_name': '公司基本資訊',
                'verbose_name_plural': '公司基本資訊',
                'db_table': 'basic_company_information',
                'indexes': [models.Index(fields=['stk_no'], name='basic_compa_stk_no_9a7a09_idx')],
                'constraints': [models.UniqueConstraint(fields=('stk_no',), name='basic_company_information unique key')],
            },
        ),
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_date', models.DateField(default=django.utils.timezone.now, verbose_name='成交日期')),
                ('price', models.FloatField(verbose_name='成交價格')),
                ('qty', models.IntegerField(verbose_name='成交數量')),
                ('fee', models.IntegerField(verbose_name='手續費')),
                ('tax', models.IntegerField(verbose_name='交易稅')),
                ('stk_no_id', models.ForeignKey(help_text='股票代號', on_delete=django.db.models.deletion.CASCADE, to='trade.basiccompanyinformation')),
            ],
            options={
                'verbose_name': '交易明細',
                'verbose_name_plural': '交易明細',
                'db_table': 'trade_details',
            },
        ),
        migrations.CreateModel(
            name='TradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_avg', models.FloatField(verbose_name='成交均價')),
                ('qty', models.IntegerField(verbose_name='庫存股數')),
                ('initial_funds', models.FloatField(verbose_name='初始資金')),
                ('remaining_funds', models.IntegerField(verbose_name='剩餘資金')),
                ('stk_no_id', models.ForeignKey(help_text='股票代號', on_delete=django.db.models.deletion.CASCADE, to='trade.basiccompanyinformation')),
            ],
            options={
                'verbose_name': '庫存總計',
                'verbose_name_plural': '庫存總計',
                'db_table': 'trade_summary',
            },
        ),
    ]
