# Generated by Django 5.1.1 on 2024-12-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesummary',
            name='value_total',
        ),
        migrations.AddField(
            model_name='tradesummary',
            name='hold_qty_price',
            field=models.IntegerField(default=0, verbose_name='購買成本'),
        ),
        migrations.AddField(
            model_name='tradesummary',
            name='now_qty_price',
            field=models.IntegerField(default=0, help_text='股數x最新股價', verbose_name='最新價值'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='fee',
            field=models.IntegerField(default=0, verbose_name='手續費'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='funds_invested',
            field=models.IntegerField(default=0, help_text='只有設定時會變動', verbose_name='投入資金'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='funds_remaining',
            field=models.IntegerField(default=0, help_text='買賣後剩下資金，投入資金變動時也會增減', verbose_name='剩餘資金'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='hold_qty_price',
            field=models.IntegerField(default=0, verbose_name='購買成本'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='note',
            field=models.CharField(default='', max_length=30, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='price',
            field=models.FloatField(default=0, verbose_name='成交價格'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='price_avg',
            field=models.FloatField(default=0, verbose_name='成交均價'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='成交數量'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='qty_price',
            field=models.IntegerField(default=0, help_text='股數x金額', verbose_name='價值金額'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='持有股數'),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='tax',
            field=models.IntegerField(default=0, verbose_name='交易稅'),
        ),
        migrations.AlterField(
            model_name='tradesummary',
            name='funds_invested',
            field=models.IntegerField(default=0, verbose_name='投入資金'),
        ),
        migrations.AlterField(
            model_name='tradesummary',
            name='funds_remaining',
            field=models.IntegerField(default=0, help_text='買賣後剩下資金', verbose_name='剩餘資金'),
        ),
        migrations.AlterField(
            model_name='tradesummary',
            name='price',
            field=models.FloatField(default=0, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='tradesummary',
            name='price_avg',
            field=models.FloatField(default=0, verbose_name='成交均價'),
        ),
        migrations.AlterField(
            model_name='tradesummary',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='持有股數'),
        ),
    ]
